language: java
# install: ant deps

before_install:
  - java -version

script: 
  - jdk_switcher use oraclejdk8
  - ./build_processing.sh
  - ./build_hello_world.sh
  - ./build_hell_world.sh

after_failure:
  - find . | egrep "processing-java"
  - find .

after_success:
  - find . | egrep "processing-java"
  - find .
