language: java
# install: ant deps

before_install:
  - java -version

script: 
  - jdk_switcher use oraclejdk8
  - ./build_processing.sh
  - ./build.sh

after_failure:
  - find .
  - java -version

after_success:
  - find .
  - java -version
